[package]
name = 'MultiSender'
version = '1.0.0'
authors = []

[addresses]
std="0x1"
my_addrx="0x123"

[dev-addresses]

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dev-dependencies]
