[package]
name = 'multi_sender'
version = '1.0.0'
authors = []

[addresses]
std="0x1"
my_addrx="c274ad80a03f026b8f2b33e72f7c53a06aefa52285700464566d62e2b64ed09b"

[dev-addresses]

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dev-dependencies]
